AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ecs-fargate-task-family
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue codebuild-sample-ecs-service-role
      TaskRoleArn: !ImportValue codebuild-sample-ecs-service-role
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: ecs-fargate-container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/ecs-fargate-task
          PortMappings:
            - ContainerPort: 80
  FargateService:
    Type: AWS::ECS::Service
    DependsOn: TaskDefinition
    Properties:
      Cluster: !ImportValue apps-ecs-cluster
      ServiceName: ecs-fargate-service
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          # Subnets:
          #   - vpcSubnet1
          #   - vpcSubnet2
          # SecurityGroups:
          #   - vpcSecurityGroup
