AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TaskDefinitionName:
    Type: String
    Default: ecsFargateTask
  ClusterName:
    Type: String
    Default: ecsCluster
  ServiceName:
    Type: String
    Default: ecs-fargate-service
  ContainerName:
    Type: String
    Default: ecs-fargate-container
  Image:
    Type: String
    Default: my-ecr-repo:latest
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskDefinitionName
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !ImportValue codebuild-sample-ecs-service-role
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Sub ${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/ecs-fargate-task
          PortMappings:
            - ContainerPort: 80
  FargateService:
    Type: AWS::ECS::Service
    DependsOn: TaskDefinition
    Properties:
      Cluster: !Ref Cluster
      ServiceName: !Ref ServiceName
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - vpcSubnet1
            - vpcSubnet2
          SecurityGroups:
            - vpcSecurityGroup
