AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TaskDefinitionName:
    Type: String
    Default: my-fargate-task
  ClusterName:
    Type: String
    Default: my-ecs-cluster
  ContainerName:
    Type: String
    Default: my-container
  Image:
    Type: String
    Default: my-ecr-repo:latest
  ScheduleExpression:
    Type: String
    Default: cron(0 10 * * ? *)
Resources:
  ScheduledTask:
    Type: AWS::Events::Rule
    Properties:
      Description: Scheduled task rule
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt FargateService.Arn
          Id: fargate-service
  FargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskDefinitionName
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ecsTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: 80
  FargateService:
    Type: AWS::ECS::Service
    DependsOn:
      - ScheduledTask
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: 1
      TaskDefinition: !Ref FargateTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue vpcSubnet1
            - !ImportValue vpcSubnet2
          SecurityGroups:
            - !ImportValue vpcSecurityGroup
